apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingappimg-deploy
  labels:
    app: bankingappimg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankingappimg
  template:
    metadata:
      labels:
        app: bankingappimg
    spec:
      containers:
      - name: bankingappimg-container
        image: shadab55/bankingappimg
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankingappimg-np-service
  labels:
    app: bankingappimg
spec:
  selector:
    app: bankingappimg

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
